# scripts/vivado_impl_reports.tcl
# Generate Vivado out-of-context synthesized and post-route timing/utilization/power reports
# for the Verilog RTL generated by Vitis HLS.
#
# Run from repository root after:
#   vitis_hls -f hls/run_hls.tcl
#
# Then:
#   vivado -mode batch -source scripts/vivado_impl_reports.tcl

set repo_root [pwd]
set rtl_dir "$repo_root/jpegls_hls_prj/solution1/syn/verilog"
set reports_dir "$repo_root/reports"

puts "INFO: repo_root   = $repo_root"
puts "INFO: rtl_dir     = $rtl_dir"
puts "INFO: reports_dir = $reports_dir"

file mkdir $reports_dir

if {![file exists $rtl_dir]} {
    puts "ERROR: HLS Verilog RTL directory not found: $rtl_dir"
    puts "Run first: vitis_hls -f hls/run_hls.tcl"
    exit 1
}

set rtl_files [glob -nocomplain "$rtl_dir/*.v"]

if {[llength $rtl_files] == 0} {
    puts "ERROR: No Verilog files found in $rtl_dir"
    exit 1
}

puts "INFO: Found RTL files:"
foreach f $rtl_files {
    puts "  $f"
}

# Important: use out-of-context implementation for an HLS IP.
# Otherwise Vivado treats the wide AXI interfaces as package pins and placement can fail
# with an IO overutilization error.
create_project -force jpegls_vivado_ooc_impl "$repo_root/vivado_ooc_impl_prj" -part xc7z020clg484-1

add_files $rtl_files
set_property top jpegls_encode_hls [current_fileset]
update_compile_order -fileset sources_1

puts "INFO: Running out-of-context synthesis..."
synth_design \
    -top jpegls_encode_hls \
    -part xc7z020clg484-1 \
    -mode out_of_context

if {[llength [get_ports -quiet ap_clk]] == 0} {
    puts "ERROR: ap_clk port not found after synthesis. Check generated HLS top ports:"
    puts "  grep -R \"module jpegls_encode_hls\" -n jpegls_hls_prj/solution1/syn/verilog"
    exit 1
}

create_clock -name ap_clk -period 10.000 [get_ports ap_clk]

puts "INFO: Writing synthesized OOC reports..."
report_timing_summary \
    -file "$reports_dir/vivado_synth_timing.rpt" \
    -max_paths 10

report_utilization \
    -file "$reports_dir/vivado_synth_utilization.rpt" \
    -hierarchical

report_power \
    -file "$reports_dir/vivado_synth_power.rpt"

puts "INFO: Running out-of-context implementation..."
opt_design
place_design
route_design

puts "INFO: Writing post-route OOC reports..."
report_timing_summary \
    -file "$reports_dir/vivado_timing.rpt" \
    -max_paths 10

report_utilization \
    -file "$reports_dir/vivado_utilization.rpt" \
    -hierarchical

report_power \
    -file "$reports_dir/vivado_power.rpt"

write_checkpoint -force "$reports_dir/jpegls_post_route_ooc.dcp"

puts "INFO: DONE. Generated reports:"
puts "  $reports_dir/vivado_synth_timing.rpt"
puts "  $reports_dir/vivado_synth_utilization.rpt"
puts "  $reports_dir/vivado_synth_power.rpt"
puts "  $reports_dir/vivado_timing.rpt"
puts "  $reports_dir/vivado_utilization.rpt"
puts "  $reports_dir/vivado_power.rpt"
puts "  $reports_dir/jpegls_post_route_ooc.dcp"

exit 0
